additional_parameters = ""
async_upload = false
base_weights_multiplier = 1
blocks_to_swap = 13
caching_latent_batch_size = 1
caching_latent_device = "cuda"
caching_latent_keep_cache = true
caching_latent_num_workers = 2
caching_latent_skip_existing = true
caching_teo_batch_size = 4
caching_teo_device = "cuda"
caching_teo_fp8_text_encoder = false
caching_teo_keep_cache = true
caching_teo_num_workers = 2
caching_teo_skip_existing = true
caption_strategy = "folder_name"
compile = true
compile_backend = "inductor"
compile_cache_size_limit = 0
compile_dynamic = "auto"
compile_fullgraph = false
compile_mode = "default"
control_directory_name = "control_images"
control_resolution_height = 2024
control_resolution_width = 2024
create_missing_captions = true
dataset_batch_size = 1
dataset_bucket_no_upscale = false
dataset_cache_directory = "cache_dir"
dataset_caption_extension = ".txt"
dataset_config = "G:/SECourses_Musubi_Trainer_v29/dont_upload/FLUX_Klein4b\\flux_dataset_20260204-180434.toml"
dataset_config_mode = "Generate from Folder Structure"
dataset_enable_bucket = true
dataset_resolution_height = 1024
dataset_resolution_width = 1024
ddp_gradient_as_bucket_view = false
ddp_static_graph = false
ddp_timeout = 0
debug_mode = "None"
dim_from_weights = false
disable_numpy_memmap = false
discrete_flow_shift = 1
dit = "G:/SECourses_Musubi_Trainer_v29/Training_Models_FLUX_2_and_Klein/FLUX2-Klein-Base-4B.safetensors"
dynamo_backend = "no"
dynamo_mode = ""
dynamo_use_dynamic = false
dynamo_use_fullgraph = false
extra_accelerate_launch_args = ""
flash_attn = false
fp8_base = true
fp8_scaled = true
fp8_text_encoder = false
full_bf16 = false
full_fp16 = false
generated_toml_path = "G:/SECourses_Musubi_Trainer_v29/dont_upload/FLUX_Klein4b\\flux_dataset_20260204-180434.toml"
gpu_ids = "0"
gradient_accumulation_steps = 1
gradient_checkpointing = true
gradient_checkpointing_cpu_offload = false
img_in_txt_in_offloading = false
learning_rate = 6e-5
log_config = false
log_prefix = ""
log_tracker_name = ""
log_with = ""
logging_dir = ""
lr_decay_steps = 0
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_min_lr_ratio = 0
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_scheduler_timescale = 0
lr_scheduler_type = ""
lr_warmup_steps = 0
main_process_port = 0
max_data_loader_n_workers = 2
max_grad_norm = 0
max_timestep = 1000
max_train_epochs = 200
max_train_steps = 80000
mem_eff_save = false
metadata_author = ""
metadata_description = ""
metadata_license = ""
metadata_tags = ""
mixed_precision = "bf16"
model_family = "FLUX Klein"
model_version = "klein-base-4b"
multi_gpu = false
network_alpha = 128
network_args = []
network_dim = 128
network_dropout = 0
network_module = "networks.lora_flux_2"
no_metadata = false
no_resize_control = true
num_cpu_threads_per_process = 1
num_machines = 1
num_processes = 1
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
optimizer_type = "AdaFactor"
output_dir = "G:/SECourses_Musubi_Trainer_v29/dont_upload/FLUX_Klein4b"
output_name = "My_FLUX_Klein_4B_LoRA"
parent_folder_path = "C:\\Users\\Furkan\\Pictures\\3_img"
persistent_data_loader_workers = true
sage_attn = false
sample_at_first = false
sample_every_n_epochs = 0
sample_every_n_steps = 0
sample_guidance_scale = 4
sample_height = 1024
sample_negative_prompt = ""
sample_output_dir = ""
sample_seed = 42
sample_steps = 50
sample_width = 1024
save_every_n_epochs = 1
save_every_n_steps = 0
save_state = false
save_state_on_train_end = false
save_state_to_huggingface = false
scale_weight_norms = 0
sdpa = true
seed = 42
sigmoid_scale = 1
split_attn = false
text_encoder = "G:/SECourses_Musubi_Trainer_v29/Training_Models_FLUX_2_and_Klein/qwen_3_4b.safetensors"
timestep_sampling = "flux2_shift"
training_comment = ""
training_mode = "LoRA Training"
use_pinned_memory_for_block_swap = false
vae = "G:/SECourses_Musubi_Trainer_v29/Training_Models_FLUX_2_and_Klein/FLUX_2_Klein_Train_VAE.safetensors"
vae_dtype = "float32"
wandb_run_name = ""
weighting_scheme = "none"
xformers = false
